/*
 * generated by Xtext
 */
package org.euro2016.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EntitiesUiModule extends org.euro2016.ui.AbstractEntitiesUiModule {
	public EntitiesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
