/*
 * generated by Xtext
 */
package org.euro2016.ui.contentassist

import org.euro2016.ui.contentassist.AbstractEntitiesProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class EntitiesProposalProvider extends AbstractEntitiesProposalProvider {
}
